### ISSUE TITLE
Fixing the default headers has broken non JSON tests

### ISSUE THREAD

**Issue by simmogs** [EDMC/api-versions#13]
I'm using Rails 4 and Ruby 2.0. The change to setting default headers breaks all my none JSON tests. My Rails app has some HTML pages as well. The error I get is:

```
ActionController::UnknownFormat (ActionController::UnknownFormat)
./features/step_definitions/user_steps.rb:42:in `sign_in'
./features/step_definitions/user_steps.rb:74:in `/^I sign in with valid credentials$/'
features/users/sign_in.feature:22:in `When I sign in with valid credentials'
```

I used Rails composer to create the basic framework so the tests are their defaults.

If I revert to the latest published gem (1.2.0) everything is ok again.

**Comment by rposborne** [comment]
It appears 1.2.1 includes this reasonably substantial behavior change that injects the vnd+ request header in all incoming requests, unless a version is already specified.  This is where the behavior change occurred 6a8a6dcf83,   I think this should be unless ```.blank?``` so it only defaults when no accept is passed. 

I think this is a pretty substantial behavior change to only be a patch release and it might be just a smell as this modifies ALL incoming requests regardless if it's directed at an API controller or not.

**Comment by pmackay** [comment]
I think this broke with this change https://github.com/EDMC/api-versions/commit/a73cbadf1bec7d092af3801b24db69ab35f18cde. I've just tried this gem on a project and hit this issue. Seems to work OK by dropping back to v1.2.0.
